
#GET http://localhost:3000/user




 #POST http://localhost:8080/user HTTP/1.1
 #content-type: application/json

 #{   
 #  "password": "fatAnnie",
#   "username": "Annie",
#}


# PUT http://localhost:8080/user/3
# content-type: application/json

# {
#   "username": "Billy",
#   "password": "password"
# }

# DELETE http://localhost:8080/user/2